export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_RESPONSE = 'POST_LIST_RESPONSE';
export const POST_LIST_ERROR = 'POST_LIST_ERROR';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_RESPONSE = 'POST_CREATE_RESPONSE';