export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_RESPONSE = 'POST_LIST_RESPONSE';
export const POST_LIST_ERROR = 'POST_LIST_ERROR';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_RESPONSE = 'POST_CREATE_RESPONSE';

export const POST_DELETE = 'POST_DELETE';
export const POST_UPDATE = 'POST_UPDATE';

export const CREATE_USER = 'CREATE_USER';
export const GET_USER_TOKEN = 'GET_USER_TOKEN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';